AllCops:
  TargetRubyVersion: 2.4

Metrics/LineLength:
  Max: 120

Style/AndOr:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: false

SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
