#!/usr/bin/env ruby

require 'pry'
require 'csv'
require 'bigdecimal'
require 'date'
require 'readline'
require 'optparse'
require 'optparse/date'
require 'openssl'
require 'io/console'

dir = File.expand_path(File.dirname(__FILE__))
Dir.glob(File.join(dir, 'lib', '*.rb')).each { |file| require_relative file }

ledger = ENV['LEDGER']

fail ArgumentError, 'Environment variable LEDGER with the location of the ledger file must be specified' unless ledger

LEDGER = File.new(File.expand_path(ledger))

options = UI.new.tap(&:run).options

ledger = Ledger.new

ledger.encrypt! and exit if options[:encrypt]
ledger.decrypt! and exit if options[:decrypt]

ledger.load!
printer = Printer.new(ledger)

ledger.add! if options[:add]
printer.balance if options[:balance]
printer.categories if options[:categories]
printer.transactions if options[:transactions]
printer.travels(options[:travels]) if options[:travels]
printer.report(options[:report]) if options[:report]
