#!/usr/bin/env ruby

require 'pry'
require 'csv'
require 'bigdecimal'
require 'date'
require 'readline'
require 'optparse'
require 'optparse/date'
require 'openssl'
require 'tempfile'
require 'money'
require 'money/bank/google_currency'
require 'yaml'
require 'erb'
require_relative 'lib/ui'

# Money configurations
I18n.enforce_available_locales = false
Money.default_bank = Money::Bank::GoogleCurrency.new

# Configurations
opts = UI.new.tap(&:run).options

puts 'Configuration file not found' or exit unless File.exist?(opts[:config])

CONFIGS = YAML.safe_load(ERB.new(File.read(opts[:config])).result, [Symbol]).freeze

Dir.glob(File.join(__dir__, 'lib', '*.rb')).each { |file| require file }

Ledger.new.create! or exit if ARGV[0] == 'create'

case
when opts[:add]        then Ledger.new.add!(opts[:transaction])
when opts[:open]       then Ledger.new.open!
when opts[:balance]    then Printer.new.balance
when opts[:categories] then Printer.new.categories
when opts[:list]       then Printer.new.list
when opts[:trips]      then Printer.new.trips(opts[:trips])
when opts[:report]     then Printer.new.report(opts[:report])
end
