#!/usr/bin/env ruby

require 'pry'
require 'csv'
require 'bigdecimal'
require 'date'
require 'readline'
require 'optparse'
require 'optparse/date'
require 'openssl'
require 'io/console'
require 'money'

I18n.enforce_available_locales = false

Dir.glob(File.join(File.expand_path(File.dirname(__FILE__)), 'lib', '*.rb')).each { |file| require_relative file }

ledger = ENV['LEDGER']

fail ArgumentError, 'Environment variable LEDGER with the location of the ledger file must be specified' unless ledger

LEDGER = File.new(File.expand_path(ledger))

options = UI.new.tap(&:run).options

ledger = Ledger.new

case
when options[:add]     then ledger.add!
when options[:open]    then ledger.open!
when options[:decrypt] then ledger.decrypt!
when options[:encrypt] then ledger.encrypt!
end

ledger.load!
printer = Printer.new(ledger)

case
when options[:balance]      then printer.balance
when options[:categories]   then printer.categories
when options[:transactions] then printer.transactions
when options[:trips]        then printer.trips(options[:trips])
when options[:report]       then printer.report(options[:report])
end
